server:
  port: 8761  # Port for Eureka server

eureka:
  client:
    registerWithEureka: false  # Eureka server itself doesn't register with another Eureka server
    fetchRegistry: false  # No need to fetch registry
  server:
    enableSelfPreservation: false  # Disable self-preservation mode